# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/crystallang/crystal/
image: "crystallang/crystal:latest-alpine"

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
# services:
#   - mysql:latest
#   - redis:latest
#   - postgres:latest

# variables:
#   POSTGRES_DB: database_name

# Cache shards in between builds
cache:
  paths:
    - lib

# This is a basic example for a shard or script which doesn't use
# services such as redis or postgres
before_script:
  - apk --update add libxml2
  - crystal -v  # Print out Crystal version for debugging
  - shards install

# If you are using built-in Crystal Spec.
"spec & format":
  script:
    - crystal spec
    - crystal tool format --check

pages:
  stage: deploy
  script:
    - crystal docs -o public src/webmention.cr
  artifacts:
    paths:
      - public
  only:
    - master
